// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xtqcahumyyvngfvrcmci.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh0cWNhaHVteXl2bmdmdnJjbWNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyODY0OTAsImV4cCI6MjA2NDg2MjQ5MH0.arW3kI7lFmCEp6WhJdeGqsksxIsIBbjCwwka_V9WxKI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);